### ISSUE TITLE
启动后报错，登录不了

### ISSUE THREAD

**Issue by GitKou** [kenberkeley/vue-demo#10]
![image](https://cloud.githubusercontent.com/assets/7437397/19915847/124bb05a-a0f0-11e6-87ee-4ef892602de2.png)
![image](https://cloud.githubusercontent.com/assets/7437397/19915878/53fc03d8-a0f0-11e6-98e8-69a7b786b638.png)

**Comment by kenberkeley** [comment]
请参照 [issue2](https://github.com/kenberkeley/vue-demo/issues/2) 部署
