### ISSUE TITLE
希望可以做 vue2 的版本

### ISSUE THREAD

**Issue by imagine10255** [kenberkeley/vue-demo#12]
很棒的Demo
希望可以做 vue2 的版本

**Comment by kenberkeley** [comment]
最近在项目执行中，发现本 demo 的一些问题
尤其是 `components/` 与 `views/` 的区别

往后会把 `components/` 中的一些所谓的 `容器组件（抄袭 React 的说法）` 移到 `views/` 中
使得 `components/` 存放的是纯粹的、封装完好的组件

好了，在此回应您的需求
由于 Vue 的版本与项目的组织架构并没有特别大的关联
因此您也可以自行搭建出 Vue 2 版本的项目结构

**Comment by imagine10255** [comment]
感謝您的回覆！目前還在學習中
因為會有些在 Vue 1 版本時的方法 被 Vue 2 廢除
所以學習 Vue 1 的架構再轉到 Vue 2 會有些混亂

**Comment by kenberkeley** [comment]
其实很多项目一旦做下来，基本就不会折腾说要升级版本
当然，如果您是为未来的升级考虑，那还不如直接上手 Vue 2
或遵循 http://cn.vuejs.org/v2/guide/migration.html 避免使用部分废弃特性

**Comment by kenberkeley** [comment]
Vue2 脚手架已出！！！ #26
