### ISSUE TITLE
按照issue2启动后浏览器显示：Cannot GET /, console里面有error: Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by iedwin** [kenberkeley/vue-demo#13]
Cannot GET /
Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by kenberkeley** [comment]
抱歉，回复迟了
请问问题解决了吗？

**Comment by iedwin** [comment]
@kenberkeley 谢谢！问题还没有解决呢。
npm start 报错：
ERROR in ./~/babel-loader!./~/eslint-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/App.vue
Module not found: Error: Cannot resolve 'file' or 'directory' /home/edwin/WORKSPACE/CODE/Edwin/Vue/vue-demo/src/components/Navbar in /home/edwin/WORKSPACE/CODE/Edwin/Vue/vue-demo/src/components
 @ ./~/babel-loader!./~/eslint-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/App.vue 7:14-42

看起来是App.vue中第１４行找不到这个Navbar，不清楚是什么情况。

```
import Navbar from 'COMPONENT/Navbar/'
```

**Comment by kenberkeley** [comment]
如果说 Navbar 组件真的在那个位置而还是报错的话，我就真的无能为力了。

**Comment by iedwin** [comment]
嗯，我没有动代码，只是单纯的npm start而已。
难道是我的系统有问题？Ubuntu 16.04。

**Comment by iedwin** [comment]
@kenberkeley 貌似确实和系统、环境有关系，我用mac是可以启动起来的，不会报错。
原因不明 -）

**Comment by kenberkeley** [comment]
看来我找到原因了：Git 的大小写问题
![qq 20161111101805](https://cloud.githubusercontent.com/assets/13287948/20202175/3d97d7e8-a7f8-11e6-9718-2dd666ba8acb.png)

**Comment by kenberkeley** [comment]
在操作系统层面上，我们是看不到 `navbar/` 这个文件夹的

**Comment by kenberkeley** [comment]
见 commit [c7f944](https://github.com/kenberkeley/vue-demo/commit/c7f944180493c818e2be37aebc542106b5530391)
