### ISSUE TITLE
所有环境安装好，但是不能正确的 build

### ISSUE THREAD

**Issue by KonishiLee** [kenberkeley/vue-demo#17]
![Uploading image.png…]()

**Comment by kenberkeley** [comment]
报错信息？

**Comment by KonishiLee** [comment]
![Uploading image.png…]()
一直贴图，贴不出来

**Comment by KonishiLee** [comment]
ERROR in ./src/app.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/pj/Desktop/github-package/vue-demo"

**Comment by kenberkeley** [comment]
建议使用 `cnpm` 重新安装依赖：
```
$ cd vue-demo
$ rm -rf node_modules
$ npm i cnpm -g
$ cnpm i
```

**Comment by KonishiLee** [comment]
我可能知道原因了，这个项目我已经 clone 很久了，一直没时间看，node_modules 里面的 package 也是以前 install 的，所以可能版本冲突导致，马上我重新 install 一下。
