### ISSUE TITLE
详细说下你这个项目怎么打开好吗

### ISSUE THREAD

**Issue by TopCuii** [kenberkeley/vue-demo#2]
讲道理

我这边打开很是问题啊

**Comment by kenberkeley** [comment]
@TopCuii

首先，您需要打开两个命令窗口，记为窗口 A  和窗口 B
窗口 A 用于启动前端开发服务器，窗口 B 用于启动后端 RESTful API  

假设您想在 `/Users/ken/` 目录下存放项目代码，那就**分别**在窗口 A B 敲下：`cd /Users/ken` 切换到该路径  

之后，在窗口 B 中敲下：

```
$ git clone https://github.com/kenberkeley/msg-board-api.git`
### 拉取代码...

$ cd msg-board-api
$ npm install
### 安装依赖...

$ npm start
```

同样地，在窗口 A 中敲下：

```
$ git clone https://github.com/kenberkeley/vue-demo.git
$ cd vue-demo
$ npm install
$ npm start
```

编译完毕后，默认情况下浏览器会自动弹出并访问 `localhost:8080`

> 注意：本项目为实现跨平台，需要全局安装：`npm i cross-env -g`

**Comment by wuxiangwa** [comment]
...msgRoutes   想问一下这个是什么意思，如果我下再加一个该怎么写

**Comment by kenberkeley** [comment]
@wuxiangwa 这是 ES6 的解构特性，了解后您就可以知道怎么写了

**Comment by wuxiangwa** [comment]
谢谢。这个问题我明白了。  我 加载element的库时会报错
import 'element-ui/lib/theme-default/index.css'
报错
in ./~/.1.0.2@element-ui/lib/theme-default/fonts/element-icons.eot?t=1472440741
Module parse failed: /Applications/XAMPP/xamppfiles/htdocs/my_demo/vue-demo/node_modules/.1.0.2@element-ui/lib/theme-default/fonts/element-icons.eot?t=1472440741 Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.

**Comment by kenberkeley** [comment]
@wuxiangwa 或许这个 [issue](https://github.com/webpack/css-loader/issues/18) 可以帮到您

**Comment by kenberkeley** [comment]
@wuxiangwa 感谢您让我发现了一个 bug。。。貌似是之前全局替换的时候的疏漏
您的这个问题已经修复，见 [8a50f9](https://github.com/kenberkeley/vue-demo/commit/8a50f925e2b10bb8c74885a3c35a11232d244fd1)

**Comment by wuxiangwa** [comment]
好的 十分感谢 问题解决了

**Comment by wuxiangwa** [comment]
您好！昨天的问题谢谢您给我解答。今天又遇到新的问题
代码：
import DataTable from 'vue-datatable'
Vue.use(DataTable)
错误信息：
ERROR in ./~/.1.0.4@vue-datatable/src/DataTable.vue
Module parse failed: /Applications/XAMPP/xamppfiles/htdocs/my_demo/vue-demo/node_modules/.1.0.4@vue-datatable/src/DataTable.vue Unexpected token (1:0)
You may need an appropriate loader to handle this file type.

**Comment by kenberkeley** [comment]
`build/webpack.base.conf.js` 中存在以下代码（L47）：
```
    loaders: [{
      test: /\.vue$/,
      loader: 'vue',
      include: src,
      exclude: /node_modules/ // <----- 就是这里
    }
```

**Comment by kenberkeley** [comment]
@wuxiangwa 可以参考这里 https://github.com/webpack/webpack/issues/2031

**Comment by wuxiangwa** [comment]
您好！谢谢您之前的解答。我又来问问题了！
代码：
 msgService
        .fetch({
          author: this.$route.query.author,
          pageIdx: this.pageIdx,
          quantity: this.quantity
        })
        .then(msgs => this.msgs = msgs)
我想理解您的这一块的代码  应该看哪方面的资料

**Comment by kenberkeley** [comment]
@wuxiangwa http://es6.ruanyifeng.com/

**Comment by wuxiangwa** [comment]
您好
代码：
menusList.forEach(function(menu) {
                        menu.subMenus = _.filter(subMenuList, {'parent_id': menu.id})
                    })
我用的lodash的方法
 error  no-undef  "_" is not defined  
![Uploading image.png…]()
没出来的是下划线

**Comment by kenberkeley** [comment]
@wuxiangwa 抱歉，我在上班
我衷心建议您通过搜索引擎自行解决问题
授人以鱼不如授人以渔

**Comment by wuxiangwa** [comment]
好的 谢谢
