### ISSUE TITLE
你好，请问有Vue2.0版本？

### ISSUE THREAD

**Issue by luuman** [kenberkeley/vue-demo#20]
browser-sync-webpack-plugin 不是可以自动生成ip地址的？

**Comment by luuman** [comment]
不好意思，打扰了，对webpack配置不太熟悉

**Comment by kenberkeley** [comment]
有关 Vue 2.x 版本见 #16 

[browser-sync-webpack-plugin](https://github.com/Va1/browser-sync-webpack-plugin) 的用法见其项目介绍

**Comment by luuman** [comment]
谢谢

**Comment by kenberkeley** [comment]
Vue2 脚手架已出！！！ #26
