### ISSUE TITLE
想搭建这个demo的vue2.0要注意什么

### ISSUE THREAD

**Issue by luuman** [kenberkeley/vue-demo#22]

**Comment by kenberkeley** [comment]
我向来不建议别人在实际项目中使用 Vue2.x
但如果说真的要上的话，最好：
1. 升级 Webpack 2.x
2. 升级 ESLint 3.x
3. Vue 全家桶都得升，注意 Vue 1.x 与 2.x 的[区别](https://github.com/vuejs/vue/issues/2873)

**Comment by luuman** [comment]
最近刚开始学vue 2.0，觉得你的项目结构很赞，而且公司要用2.0，

**Comment by kenberkeley** [comment]
那这样的话，只需要不使用 Vue 1.x 的语法，升级一下 loader 就好了，其他可以暂时不折腾

**Comment by luuman** [comment]
恩，暂时还在看vue 的文档，

**Comment by kenberkeley** [comment]
推荐 http://cn.vuejs.org/v2/guide/migration.html

**Comment by luuman** [comment]
我现在就是想，先把环境好，之后再研究你的代码！只是大概的骨架

**Comment by luuman** [comment]
webpack升级2.0之后，打包还能使用？会报错

**Comment by luuman** [comment]
应为之前我一直是使用gulp搭建的

**Comment by kenberkeley** [comment]
Webpack 1.x 和 2.x 的变化也比较大，见 [Migrating from v1 to v2](https://webpack.js.org/guides/migrating/)

**Comment by kenberkeley** [comment]
Vue2 脚手架已出！！！ #26
