### ISSUE TITLE
本人新手，疑惑中……

### ISSUE THREAD

**Issue by JasonLisa** [kenberkeley/vue-demo#24]
## 作者写的如
`/**
   * 新增留言信息
   * @param   {String} msgBody.title
   * @param   {String} msgBody.content
   * @resolve {Object} msg
   */
  add (msgBody) {
    return xhr({
      method: 'post',
      url: '/msg',
      body: msgBody
    })
  }`
意思是点击添加按钮的时候，调用后台的处理方法msg，是这意思吗？？

**Comment by kenberkeley** [comment]
这其实是一个 xhr 封装，源码见 https://github.com/kenberkeley/vue-demo/blob/master/src/services/xhr/jquery.js

**Comment by JasonLisa** [comment]
谢谢！！好像明白点了。我看了一下
```
// 后端 API 根路径
export const rootPath = '/api'
```
我是不是可以这样理解：如果我的后端用java写的，那么前端和后端可以部署在一个服务器上同一个tomcat的两个实例。形如 rootPath ＝'http://10.24.100.220/api' 而前前端的访问地址可以是http://10.24.100.220/vue-demo/dist/#!/msg/add。但实际上他们是两个tomcat实例。是不是可以这样理解？？？

**Comment by kenberkeley** [comment]
我不熟悉 Java，但这种静态资源一般都是使用 Nginx 部署，然后使用 `proxy_pass` 转发到后端 API。就算不用 Nginx 部署，纯用 Express.js，也只需要一个实例（监听一个端口）即可完成部署。

**Comment by JasonLisa** [comment]
谢谢！
