### ISSUE TITLE
关于Vue 组件中route 何时执行。

### ISSUE THREAD

**Issue by souse** [kenberkeley/vue-demo#25]
在demo中看到一段代码如下：

export default {
  mixins: [updateQuery],
  components: { Pagination, LimitSelect, AuthorSelect, OptBtnGroup },
  data: () => ({ total: 0, msgs: [] }),
  route: {
    data () {
      msgService
        .fetchList(this.$route.query)
        .then(({ total, rows }) => {
          this.total = total
          this.msgs = rows
        })
    }
  },

请教下 route什么时候执行呢， 可以用生命周期的其他方法替换在route里给data重新赋值吗？

**Comment by kenberkeley** [comment]
https://github.com/vuejs/vue-router/blob/1.0/docs/zh-cn/pipeline/data.md
