### ISSUE TITLE
build 不成功，是何原因？

### ISSUE THREAD

**Issue by jimyuan** [kenberkeley/vue-demo#3]
正在学习这个 demo 的代码架构，很棒！不过为啥我 `npm build` 后没一点反应呢? 控制台并没有输出任何 info，也没有 dist 目录生成。这个跟开不开 msg-board-api 这个项目没啥关系吧？
### 环境
- OS X 10.11.6
- node 6.3.0
- npm 3.10.3

**Comment by kenberkeley** [comment]
文档上面写的是 `npm run build` 哟

**Comment by jimyuan** [comment]
我去跳河了，大侠关了这个 issue 吧，来生见！

**Comment by kenberkeley** [comment]
@jimyuan
相关资料可搜索 npm scripts
