### ISSUE TITLE
Webpack CommonsChunkPlugin 配置 names: ['vendor', 'mainifest'] 的作用

### ISSUE THREAD

**Issue by kenberkeley** [kenberkeley/vue-demo#5]
刚才收到一份邮件：
![qq20160922-0](https://cloud.githubusercontent.com/assets/13287948/18740450/598a5f7c-80dc-11e6-8220-19094684e8ca.png)

其实很早以前我就发现，有时改动业务代码，重新 `npm run build` 编译出来的 vendor 版本号总是变化
详见 Webpack 的这个 [issue](https://github.com/webpack/webpack/issues/1315)

后来我百度到了 [webpack打包第三方类库的正确姿势](http://www.cnblogs.com/myqianlan/p/5626505.html)，貌似这就是最简单的 solution：

> 没错，就是上面这个配置，只是简单的加了 'manifest' 。
> 再次做我们前面的测试，你会发现多了一个manifest.js，但是vendor的hash值不再变化了。
> 点到为止，江湖再见。

最后，感谢 [@kinsxkins](https://github.com/kinsxkins) 的反馈

**Comment by lovetingyuan** [comment]
请问，vendor和manifest这两个名字是这个插件约定好的吗？

**Comment by kenberkeley** [comment]
@lovetingyuan https://survivejs.com/webpack/optimizing/separating-manifest/
