### ISSUE TITLE
webpack-dev-server 代理请求 api

### ISSUE THREAD

**Issue by eightfeet** [kenberkeley/vue-demo#6]
很棒，想问下开发时常用接口代理去解决跨域问题，
'''
proxy: {
  '/some/path*': {
    target: 'https://other-server.example.com',
    secure: false
  }
}
'''
这儿是怎么处理的

**Comment by kenberkeley** [comment]
首先我们来看 `build/webpack.dev.conf.js` 中
`BrowserSyncPlugin` 设置了代理 `proxy: 'http://127.0.0.1:8000/'`
该为开发服务器的地址（详见 `build/dev-server.js`）

若要跨域代理，请在 `build/dev-server.js` 中使用 [node-http-proxy](https://github.com/nodejitsu/node-http-proxy) 或者 [express-http-proxy](https://github.com/villadora/express-http-proxy) 自行实现

**Comment by eightfeet** [comment]
ok，看到
